#server:
#  port: 8080
#  servlet:
#    context-path: /
spring:
  profiles:
    active: @spring.active@
  #  datasource:
#    url: jdbc:mysql://127.0.0.1/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#    username: yunku
#    password: yunkuzhineng
#  resources:
#    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: non_null


  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 5000
    # password: redis_j
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 5
        max-wait: 10000

mybatis:
  #config-location: classpath:mapper/mapper-config.xml
  type-aliases-package:  com.yunku.demo.core.model,com.yunku.demo.core.model.example
  mapper-locations:  classpath:/mapper/*Mapper.xml
#shiro-redis.enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

wechat:
  miniAppId: wxfc703046b5bdbbe0
  miniAppSecret: ada5930a2df107749c9e93662b62bb0a

  #########   iot设备连接  ##########
iot:
  bridgeUrl: http://iotbridge01.gzyunku.net:18080

logging:
  level: {"com.yunku.demo.core.dao": "debug"}

zsession:
  key-name: token
  expriation-time: 600