server:
  port: 9001
  servlet:
    context-path: /managers-api
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: yunku
    password: yunkuzhineng